# Generated by Django 4.0.6 on 2022-07-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_issuedbook_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified_date',
        ),
    ]
