# Generated by Django 4.0.6 on 2022-07-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_issuedbook_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Borrowed'), (1, 'Available')], default=1, null=True),
        ),
        migrations.DeleteModel(
            name='IssuedBook',
        ),
    ]
